apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  selector:
    app: library
  type: NodePort
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30050
