apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  selector:
    app: bookstore
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30082
  type: NodePort
