apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  selector:
    app: bookstore
  type: NodePort
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30080
